starttime = '2016-08-01 00:00:00';
start = strcat('''',starttime,''''); % put the single quotes around it. 
stoptime  = '2016-08-03 00:00:00';
stop = strcat('''',stoptime,'''');
devices_numbers = [5390, 5419];
devices = strjoin(string(devices_numbers), ',');

shape = shapeinfo('data/ResearchAreaNH.shp');
% Boundingbox contains a 2x2 matrix with minimum and maximum lat and lon
% values, as follows:
%         Col 1     Col 2
% Row 1   min(lon)  min(lat)
% Row 2   max(lon)  max(lat)
boundingbox = shape.BoundingBox;

%%

% Overwrite boundingbox temporarily for testing purposes
% Results in 589 records
boundingbox(1,1) = -1.19;
boundingbox(2,1) = -0.64;
boundingbox(1,2) = 51.85;
boundingbox(2,2) = 52.27;

%%

javaaddpath('drivers/postgresql-42.0.0.jre7.jar');

conn = database('eecology', db_username, db_password, ...
    'org.postgresql.Driver',  'jdbc:postgresql://db.e-ecology.sara.nl:5432/eecology?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&');

setdbprefs('DataReturnFormat','structure');

%%
% For a description of the table columns, see: 
% https://public.e-ecology.sara.nl/wiki/index.php/DB_Views_2015
% 
% Query adapted from LBBG_Texel2 code from Willem Bouten and adjusted to
% only select records within the study area.
sql = strcat('SELECT t.device_info_serial, t.date_time, a.date_time, ', ...
           ' date_part(''year''::text, t.date_time) AS year, ',...
           ' date_part(''month''::text, t.date_time) AS month, ',...
           ' date_part(''day''::text, t.date_time) AS day, ',...
           ' date_part(''hour''::text, t.date_time) AS hour, ',...
           ' date_part(''minute''::text, t.date_time) AS minute, ',...
           ' date_part(''second''::text, t.date_time) AS second, ',...
           ' t.longitude, t.latitude, t.altitude, t.temperature, t.gps_fixtime, ',...
           ' t.speed_2d, t.altitude_agl, ',...
           ' t.positiondop, t.satellites_used, count(a.index) AS n_acc_points,  ',...
           ' variance(a.z_acceleration) AS z_acc_variance, ',...
           ' (t.altitude - elevation.srtm_getvalue(t."location")) AS agl, ',...
           ' p.key_name AS project',...
           ' FROM gps.ee_tracking_speed_limited t' , ... 
           ' LEFT JOIN gps.ee_acceleration_limited a' , ...
           ' ON (t.device_info_serial = a.device_info_serial AND t.date_time = a.date_time)' , ...
           ' LEFT JOIN gps.ee_tracker_ownership_limited p', ...
           ' ON (t.device_info_serial = p.device_info_serial)',...
           ' WHERE ( t.date_time >= ', start,  ')',...
           ' AND ( t.date_time <= ', stop,    ')' ,...
           ' AND ( t.device_info_serial IN (', devices, '))',... %' AND ( t.device_info_serial=' , device , ')', ... 
           ' AND ( t.longitude >= ', num2str(boundingbox(1,1)), ')', ...
           ' AND ( t.longitude <= ', num2str(boundingbox(2,1)), ')', ...
           ' AND ( t.latitude >= ', num2str(boundingbox(1,2)), ')', ...
           ' AND ( t.latitude <= ', num2str(boundingbox(2,2)), ')', ...
           ' AND t.userflag = 0',...
           ' GROUP BY p.key_name,  t.device_info_serial, t.date_time, a.date_time, t.longitude, ' , ...
           ' t.speed_2d, t.altitude_agl,' ,...
           ' t.latitude, t.altitude, t.temperature, t.gps_fixtime, t.positiondop, t.satellites_used, t.location ' , ...
           ' ORDER BY t.date_time' );
       
%%
       
curs = exec(conn,sql);
    
curs3 = fetch(curs);

%% List of all birds with tracker data in 2014 breeding season
% 2014-05-01 - 2014-07-15
devices_lbbg = [317 344 533 534 537 606 608 754 757 782 805 806 871]

devices_hg = [1600 6006 6009 6011 6015 6016 6017 6071 6072 6073 6074 6075 ...
              6076 6077 6079 6080 6082]

